server:
  tomcat:
    max-threads: 1
spring:
  spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MYSQL;INIT=runscript from 'classpath:/sql/create.sql'
    driver-class-name: org.h2.Driver
    data: classpath:/sql/tang_poetry_poetries.sql
  jpa:
    show-sql: true
    generate-ddl: true # 如果要关闭DDL，改为 false
    hibernate:
      ddl-auto: update # 把update改为 none，去掉ddl update，加快启动速度，如果修改了entity，改为update即可
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true